spring:
  config:
    import:
      - persistence-jpa-local.yml

  profiles:
    default: local

  h2:
    console:
      enabled: true

  jpa:
    open-in-view: false
    show-sql: false
    database: h2
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: false
        auto_quote_keyword: true

    defer-datasource-initialization: true
  sql:
    init:
      mode: always

  datasource:
    url: jdbc:h2:mem://localhost/~/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;DATABASE_TO_LOWER=TRUE
    username: local
    password:
